stages:
  - test

.test_template:
  stage: test
  cache:
    untracked: false
    paths:
      - $COMPOSER_HOME/cache
  artifacts:
    expire_in: 1 hour
    name: "$CI_PROJECT_PATH_SLUG-$CI_PIPELINE_ID"
    paths:
      - build/coverage
      - build/doc
  variables:
    COMPOSER_HOME: "$CI_PROJECT_DIR/build/.composer"
  script:
    - php-ext.sh enable 'xdebug'
    - setup-gitlab-token-auth.sh -- "$CI_JOB_TOKEN" "$CI_SERVER_HOST"
    - composer install --no-progress
    - phpcs $CI_PROJECT_DIR/src $CI_PROJECT_DIR/tests --standard=PSR2 -p
    - php vendor/bin/phpunit $CI_PROJECT_DIR/tests --coverage-text -vv --colors=never
    - sami update sami.php
  tags:
    - shared

test_php56:
    extends: .test_template
    image: $CI_REGISTRY/docker/alpine38-php56:v1

test_php71:
    extends: .test_template
    image: $CI_REGISTRY/docker/alpine37-php71:v2

test_php72:
    extends: .test_template
    image: $CI_REGISTRY/docker/alpine39-php72:v1

test_php73:
    extends: .test_template
    image: $CI_REGISTRY/docker/alpine312-php73:v1
