checks:
    php: true

filter:
    excluded_paths:
        - tests/*
        - vendor/*
build:
    environment:
        php:
            version: 7.2
            pecl_extensions:
                - xdebug
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
