checks:
    php: true

filter:
    excluded_paths:
        - tests/*
        - vendor/*
build:
    environment:
        php:
            version: 5.6
            pecl_extensions:
                - xdebug-2.5.5
    tests:
        override:
            -
                command: 'vendor/bin/phpunit --coverage-clover=clover.xml'
                coverage:
                    file: 'clover.xml'
                    format: 'clover'
